#ifndef _DP_CONFIG_H_
#define _DP_CONFIG_H_

#define CONFIG_MAX_DEVICE_NUM 16
#define CONFIG_USB_VENDOR_ID 0x0483
#define CONFIG_USB_PROD_ID 0xdada

#define CONFIG_DEFAULT_TIMEOUT 3000
#define CONFIG_POWER_RAMPUP_MSEC 200

#define CONFIG_MAX_DIE_COUNT 16

#define CONFIG_PROTO_BUFFER_SIZE 1024
#define CONFIG_BULK_BUFFER_SIZE 512

#endif  // #ifndef _DP_CONFIG_H_
